# Generated by Django 3.1.2 on 2020-11-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIn', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMa', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePi', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('ingredientes', models.ManyToManyField(to='MammaMia.Ingrediente')),
                ('masa', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='MammaMia.masa')),
            ],
        ),
    ]
