# Generated by Django 3.1.2 on 2020-11-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='calorias',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='masa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MammaMia.masa'),
        ),
    ]
