# Generated by Django 3.1.2 on 2020-10-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingrediente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MammaMia.ingrediente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='masa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MammaMia.masa'),
            preserve_default=False,
        ),
    ]
