# Generated by Django 3.1.2 on 2020-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0002_auto_20201030_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(upload_to='media/imgMasa'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='media/imgPizza'),
        ),
    ]
