# Generated by Django 3.1.2 on 2020-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0002_auto_20201118_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='descrip',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
