# Generated by Django 3.1.2 on 2020-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0003_masa_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=155)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=455)),
                ('pizzas', models.ManyToManyField(to='MammaMia.Pizza')),
            ],
        ),
    ]
