# Generated by Django 3.1.2 on 2020-11-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0003_auto_20201108_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
