# Generated by Django 3.1.2 on 2020-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0004_auto_20201111_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(upload_to='MammaMia/media'),
        ),
    ]
