# Generated by Django 3.1.2 on 2020-11-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0004_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevaPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ingredientes', models.ManyToManyField(to='MammaMia.Ingrediente')),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MammaMia.masa')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='masa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MammaMia.masa'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
