# Generated by Django 3.1.2 on 2020-11-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0005_auto_20201124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='descrip',
            field=models.CharField(default='', max_length=355),
            preserve_default=False,
        ),
    ]
