# Generated by Django 3.1.2 on 2020-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0006_ingrediente_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(upload_to='masas'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='pizzas'),
        ),
    ]
