# Generated by Django 3.1.2 on 2020-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0006_auto_20201112_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
