# Generated by Django 3.1.2 on 2020-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0007_auto_20201125_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=600)),
                ('numeroTelf', models.IntegerField(blank=True)),
                ('image', models.ImageField(upload_to='tiendas')),
            ],
        ),
    ]
