# Generated by Django 3.1.2 on 2020-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0007_auto_20201112_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='masa',
            name='descripcion',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masa',
            name='image',
            field=models.ImageField(default=' ', upload_to='media'),
            preserve_default=False,
        ),
    ]
