# Generated by Django 3.1.2 on 2020-11-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0008_auto_20201112_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='masa',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='MammaMia.Ingrediente'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='masas',
            field=models.ManyToManyField(to='MammaMia.Masa'),
        ),
    ]
