# Generated by Django 3.1.2 on 2020-11-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0008_direcciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='direcciones',
            new_name='Direccion',
        ),
    ]
