# Generated by Django 3.1.2 on 2020-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0009_auto_20201125_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevapizza',
            name='approvedPizza',
            field=models.BooleanField(default=False),
        ),
    ]
