# Generated by Django 3.1.2 on 2020-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0010_nuevapizza_approvedpizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevapizza',
            name='approvedPizza',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='image',
            field=models.ImageField(default='', upload_to='ingredientes'),
            preserve_default=False,
        ),
    ]
