# Generated by Django 3.1.2 on 2020-12-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0011_auto_20201129_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevapizza',
            name='crear_pizza',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MammaMia.pizza')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
