# Generated by Django 3.1.2 on 2020-12-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0012_auto_20201206_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
