# Generated by Django 3.1.2 on 2020-12-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0014_auto_20201206_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nombre',
        ),
    ]
