# Generated by Django 3.1.2 on 2020-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0015_auto_20201206_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenido',
            field=models.CharField(max_length=2500),
        ),
    ]
