# Generated by Django 3.1.2 on 2020-12-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0016_auto_20201206_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nuevaPizza',
        ),
    ]
