# Generated by Django 3.1.2 on 2020-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0017_delete_nuevapizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='/media/pizzas/pizza5.jpg', null=True, upload_to='pizzas'),
        ),
    ]
