# Generated by Django 3.1.2 on 2020-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MammaMia', '0019_auto_20201210_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='pizzas'),
        ),
    ]
